config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post 'users/guest_sign_in'=>'public/sessions#guest_sign_in'
end

scope module: :public do
	root to:"homes#top"
	get "services"=>"homes#services"
	get "privacies"=>"homes#privacies"
  resources:whiskeys do
    resources:whiskey_comments, only: [:create, :destroy]
    resource:favorites, only: [:create, :destroy]
  end
  get "searches_name"=>"searches#searches_name"
  get "searches_tag"=>"searches#searches_tag"
  get "searches_price"=>"searches#searches_price"
  get "users/unsubscribe"=>"users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal"=>"users#withdrawal", as: "withdrawal"
  get "users/user_favorites"=>"users#user_favorites"
  resources:users, only: [:show,:edit,:update]
  resources :notifications, only: [:index, :destroy]
  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
end

namespace :admin do
  root to:'homes#top'
  resources:whiskeys, only: [:show,:destroy]
  resources:users, only: [:index,:show,:edit,:update]
  resources:whiskey_comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: {maximum: 40}
  validates :email, presence: true, uniqueness: true, length: {maximum: 60}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :whiskeys, dependent: :destroy
  has_many :whiskey_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key:"visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key:"visited_id", dependent: :destroy

  validate :image_content_type, if: :was_attached?

  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg']
    errors.add(:image, "の拡張子が間違っています") unless profile_image.content_type.in?(extension)
  end

  def was_attached?
    self.profile_image.attached?
  end

  def get_profile_image
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
      profile_image
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.order('created_at DESC').page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
    @whiskeys = @user.whiskeys.order('created_at DESC').page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render "edit"
    end
  end

  private

  def user_params
     params.require(:user).permit(:name,:profile_image,:email,:is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="user_page_image">
  <div class="image">
    <h2 class="title">Profile edit</h2>

    <div class="form-group d-flex justify-content-center">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch, local:true do |f| %>
        <div class="field my-3">
          <%= f.label :"Nickname" %>
          <%= f.text_field :name, class:"form-control name" %>
        </div>
        <div class="field my-3">
          <% if @user.profile_image.blank? %>
            <%= f.label :"Profile image(＊任意)" %>
          <% else %>
            <%= f.label :"変更する場合は選択してください" %>
          <% end %>
          <%= f.file_field :profile_image, class:"form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="field my-3">
          <%= f.label :"Email" %>
          <%= f.text_field :email, class:"form-control introduction" %>
        </div>

        <div>
          <div class="mb-2">Status change</div>
          <span class="mr-4">
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, "有効", value: false %>
          </span>
          <span>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, "退会", value: true %>
          </span>
        </div>

        <div class="d-flex justify-content-center">
          <%= f.submit "更新する", class:"link my-3 text-white btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>

    <div class="form-group d-flex justify-content-center">
      <% if @user.errors.any? %>
        <%= @user.errors.count %>件のエラーが発生しました
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h2 class="title">User list</h2>
<hr>

<div class="container">
  <% @users.each do |user| %>
    <div class="row d-md-flex justify-content-md-center mt-2 mb-5 offset-md-1">
      <div class="col-4 mt-2 mr-1" >
        <%= link_to admin_user_path(user) do %>
          <%= image_tag user.get_profile_image.variant(resize_to_fill: [130, 130]), alt:"プロフィール画像" %>
        <% end %>
      </div>
      <div class="col-7 ml-md-4" >
        <div>name：<%= user.name %></div>

        <div class="mt-3">reviews：(<%= user.whiskeys.count %>)</div>

        <div class="mt-3">comments：(<%= user.whiskey_comments.count %>)</div>

        <div class="mt-3">registration status：
          <% if user.is_deleted == false %>
            有効
          <% else %>
            退会済み
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

<%= paginate @users %>

app/views/admin/users/show.html.erb
<h2 class="title">User detail</h2>

  <div class="container_fulid">
    <div class="row">
      <div class="profile_area_admin">
        <div>
          <%= image_tag @user.get_profile_image.variant(resize_to_fill: [130, 130]), alt:"プロフィール画像" %>

          <div class="mt-3">name</div>
          <p><%= @user.name %></p>

          <div>email</div>
          <p><%= @user.email %></p>

          <div>reviews：(<%= @user.whiskeys.count %>)</div>

          <div class="mt-3">comments：(<%= @user.whiskey_comments.count %>)</div>

          <div class="mt-3">registration status：
            <% if @user.is_deleted == false %>
              有効
            <% else %>
              退会済み
            <% end %>
          </div>
          <%= link_to "プロフィール編集", edit_admin_user_path(@user), class:"link my-3  text-white btn btn-sm btn-outline-secondary" %>
        </div>
      </div>

      <div class="col-sm-7 offset-md-2 mb-sm-3">
        <% unless @whiskeys.blank? %>
          <% @whiskeys.each do |whiskey| %>
            <div class="row">
              <div class="whiskey_image col-md-4 mt-md-4">
                <%= link_to admin_whiskey_path(whiskey) do %>
                 <%= image_tag whiskey.whiskey_image.variant(resize_to_fill: [260, 260]), alt: "ウイスキーの写真" %>
                <% end %>
              </div>

              <div class="col-md-7 ml-2 mb-5">
                <div class="mb-2">
                  <span class="brand">brand</span>
                  <%= whiskey.name %>
                </div>

                <div class="mb-2">
                  <span class="price">price</span>
                  <%= whiskey.price_range %>
                </div>

                <div class="taste_scent_graph">
                  <div>light</div>
                  <div class="graph1">
                    <div style="padding-left: <%= whiskey.taste %>px;"></div>
                    <div class="point"></div>
                  </div>
                  <div>rich</div>
                </div>

                <div class="taste_scent_graph">
                  <div>fruity</div>
                  <div class="graph2">
                    <div style="padding-left: <%= whiskey.scent %>px;"></div>
                    <div class="point"></div>
                  </div>
                  <div>smokey</div>
                </div>

                <div>cost performance</div>
                <div>
                  <%= render "public/whiskeys/rate", whiskey: whiskey %>
                </div>

                <div class="mt-3 mb-1">tag</div>
                <div>
                  <% if whiskey.tags.blank? %>
                    <%= "タグはありません" %>
                  <% else %>
                   #<%= whiskey.tags.map(&:tag).join(' #') %>
                  <% end %>
                </div>

                <div class="mt-3">
                  <%= "いいね数：#{whiskey.favorites.count}件" %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h3 class="no_whiskey offset-sm-2 mt-5">投稿はありません</h3>
        <% end %>
      </div>
    </div>
  </div>

<%= paginate @whiskeys %>