config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post 'users/guest_sign_in'=>'public/sessions#guest_sign_in'
end

scope module: :public do
	root to:"homes#top"
	get "services"=>"homes#services"
	get "privacies"=>"homes#privacies"
  resources:whiskeys do
    resources:whiskey_comments, only: [:create, :destroy]
    resource:favorites, only: [:create, :destroy]
  end
  get "searches_name"=>"searches#searches_name"
  get "searches_tag"=>"searches#searches_tag"
  get "searches_price"=>"searches#searches_price"
  get "users/unsubscribe"=>"users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal"=>"users#withdrawal", as: "withdrawal"
  get "users/user_favorites"=>"users#user_favorites"
  resources:users, only: [:show,:edit,:update]
  resources :notifications, only: [:index, :destroy]
  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
end

namespace :admin do
  root to:'homes#top'
  resources:whiskeys, only: [:show,:destroy]
  resources:users, only: [:index,:show,:edit,:update]
  resources:whiskey_comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/whiskey.rb
class Whiskey < ApplicationRecord

  has_one_attached :whiskey_image
  belongs_to :user
  has_many :whiskey_comments, dependent: :destroy
  has_many :whiskey_tags, dependent: :destroy
  has_many :tags, through: :whiskey_tags, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, length: { maximum: 60 }, presence: true
  validates :impression, length: { maximum: 400 }, presence: true
  validates :whiskey_image, presence: true
  validates :performance, presence: true
  has_many :notifications, dependent: :destroy

  validate :image_content_type, if: :was_attached?

  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg']
    errors.add(:image, "の拡張子が間違っています") unless whiskey_image.content_type.in?(extension)
  end

  def was_attached?
    self.whiskey_image.attached?
  end

  def self.search(word)
    Whiskey.where("name LIKE?", "%#{word}%")
  end

  def self.looks(price)
    Whiskey.where("price_range LIKE?", "#{price}")
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_whiskey_tag = Tag.find_or_create_by(tag: new)
      self.tags << new_whiskey_tag
    end
  end

  def create_notification_favorite(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and whiskey_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        whiskey_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment(current_user, whiskey_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = WhiskeyComment.select(:user_id).where(whiskey_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, whiskey_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment(current_user, whiskey_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, whiskey_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      whiskey_id: id,
      whiskey_comment_id: whiskey_comment_id,
      visited_id: visited_id,
      action: 'whiskey_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/whiskeys_controller.rb
class Admin::WhiskeysController < ApplicationController
 before_action :authenticate_admin!

  def show
   @whiskey = Whiskey.find(params[:id])
   @comments = @whiskey.whiskey_comments.order('created_at DESC').page(params[:page]).per(4)
  end

  def destroy
   @whiskey = Whiskey.find(params[:id])
   @whiskey.destroy
   redirect_to admin_root_path
  end

end

app/helpers/admin/whiskeys_helper.rb
module Admin::WhiskeysHelper
end

app/views/admin/whiskeys/show.html.erb
<h2 class="title">Review detail</h2>
<div class="container_fulid">
  <div class="row ml-md-3">
    <div class="profile_area">
      <div>
        <%= link_to admin_user_path(@whiskey.user_id) do %>
          <%= image_tag @whiskey.user.get_profile_image.variant(resize_to_fill: [130, 130]), alt: "ユーザーの写真" %>
        <% end %>

        <div class="mt-3">name</div>
        <p class="mt-1"><%= @whiskey.user.name %></p>

        <div class="mt-2 mb-5">
          <div>
            <%= link_to '投稿削除', admin_whiskey_path(@whiskey), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-7 offset-sm-2 mt-sm-3">
      <div class="row">
        <div class="whiskey_image col-md-4 mt-md-4">
          <%= image_tag @whiskey.whiskey_image.variant(resize_to_fill: [260, 260]), alt: "ウイスキーの写真" %>
        </div>

        <div class="col-md-7 ml-1 mb-5">
          <div class="mb-2">
            <span class="brand">brand</span>
            <%= @whiskey.name %>
          </div>

          <div class="d-flex">
            <div class="mr-4">impression</div>
            <!--Railsのヘルパーメソッドであるsimple_formatで、改行が反映される-->
            <div class="impression"><%= simple_format(@whiskey.impression) %></div>
          </div>

          <div class="mb-2">
            <span class="price">price</span>
            <%= @whiskey.price_range %>
          </div>

          <div class="taste_scent_graph">
            <div>light</div>
            <div class="graph1">
              <div style="padding-left: <%= @whiskey.taste %>px;"></div>
              <div class="point"></div>
            </div>
            <div>rich</div>
          </div>

          <div class="taste_scent_graph">
            <div>fruity</div>
            <div class="graph2">
              <div style="padding-left: <%= @whiskey.scent %>px;"></div>
              <div class="point"></div>
            </div>
            <div>smokey</div>
          </div>

          <div>cost performance</div>
          <div>
            <%= render "public/whiskeys/rate", whiskey: @whiskey %>
          </div>

          <div class="mt-2 mb-1">tag</div>
          <% if @whiskey.tags.blank? %>
            <%= "タグはありません" %>
          <% else %>
           #<%= @whiskey.tags.map(&:tag).join(' #') %>
          <% end %>

          <div class="mt-3">
            <%= "いいね数：#{@whiskey.favorites.count}件" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <div class="col-md-6 offset-md-3 mb-5">
    <div id="comments_area">
      <%= render "public/whiskey_comments/comments", whiskey: @whiskey, comments: @comments %>
    </div>
  </div>
</div>