config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post 'users/guest_sign_in'=>'public/sessions#guest_sign_in'
end

scope module: :public do
	root to:"homes#top"
	get "services"=>"homes#services"
	get "privacies"=>"homes#privacies"
  resources:whiskeys do
    resources:whiskey_comments, only: [:create, :destroy]
    resource:favorites, only: [:create, :destroy]
  end
  get "searches_name"=>"searches#searches_name"
  get "searches_tag"=>"searches#searches_tag"
  get "searches_price"=>"searches#searches_price"
  get "users/unsubscribe"=>"users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal"=>"users#withdrawal", as: "withdrawal"
  get "users/user_favorites"=>"users#user_favorites"
  resources:users, only: [:show,:edit,:update]
  resources :notifications, only: [:index, :destroy]
  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
end

namespace :admin do
  root to:'homes#top'
  resources:whiskeys, only: [:show,:destroy]
  resources:users, only: [:index,:show,:edit,:update]
  resources:whiskey_comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="col-md-12 mx-auto text-center pt-3">
  <i class="fab fa-facebook fa-2x"></i>

  <i class="fab fa-twitter fa-2x mx-4"></i>

  <i class="fab fa-instagram fa-2x"></i>
</div>
<div class="col-md-12 d-flex justify-content-center mx-auto py-3">
  <div class ="contacts text-center">
    <%= link_to "利用規約", services_path %>
  </div>
  <div class ="contacts text-center mx-2">
    <%= link_to "プライバシーポリシー", privacies_path %>
  </div>
  <div class ="contacts text-center">
    <% if user_signed_in? %>
      <%= link_to "お問い合わせ", new_contacts_path %>
    <% end %>
  </div>
</div>

<div class="col-md-12 mx-auto text-center">
  <p>&copy;whiskey lovers</p>
</div>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="nav header_navbar navbar navbar-expand-md navbar-dark">
    <div class="container-fluid">
        <!--ユーザー用のヘッダー-->
        <% if user_signed_in? %>
        <div class="logo">
          <a class="header_navbar navbar" href="/whiskeys"><%= image_tag 'logo.png', size: '80x80', class:"logo_size" %></a>
        </div>

        <button class="navbar-toggler mx-4" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <li class="header_link"><%= link_to "Notification", notifications_path %>
            <% if unchecked_notifications.any? %>
             <div class="check"><i class="fas fa-exclamation-triangle"></i></div>
            <% end %></li>
            <li class="header_link"><%= link_to "My page", user_path(current_user) %></li>
            <li class="header_link"><%= link_to "New post", new_whiskey_path %></li>
            <li class="header_link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <!--管理人のヘッダー-->
        <% elsif admin_signed_in? %>
        <div class="logo">
          <a class="header_navbar navbar" href="/admin"><%= image_tag 'logo.png', size: '80x80', class:"logo_size" %></a>
        </div>
        <p class="admin_title">Administrator</p>
        <button class="navbar-toggler mx-4" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="header_link"><%= link_to "User list", admin_users_path %></li>
            <li class="header_link"><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
          </ul>
        </div>
        <% else %>
        <div class="logo">
          <a class="header_navbar navbar" href="/"><%= image_tag 'logo.png', size: '80x80', class:"logo_size" %></a>
        </div>
        <button class="navbar-toggler mx-4" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="header_link"><%= link_to "Sign up", new_user_registration_path %></li>
            <li class="header_link"><%= link_to "Sign in", new_user_session_path %></li>
            <li class="header_link"><%= link_to "Guest log in", users_guest_sign_in_path, method: :post %></li>
          </ul>
        </div>
        <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_searches_form.html.erb
<h4 class="ml-4"><i class="fas fa-search"></i>Search</h4>
<div class="m-3">
  <%= form_with url: searches_name_path, local: true, method: :get do |f| %>
  <%= f.text_field :word, placeholder:"銘柄で絞り込み", size:"17x10" %>
  <%= f.submit "検索", class:"link text-white btn btn-sm btn-outline-secondary" %>
  <% end %>
</div>
<div class="m-3">
  <%= form_with url: searches_price_path, local: true, method: :get do |f| %>
  <%= f.select :price, [["〜2000円","〜2000円"],["2000円〜4000円","2000円〜4000円"],["4000円〜6000円","4000円〜6000円"],["6000円〜8000円","6000円〜8000円"],["8000円〜10000円","8000円〜10000円"],["10000円〜","10000円〜"]], {include_blank: "価格帯で絞り込み"} %>
  <%= f.submit "検索", class:"link text-white btn btn-sm btn-outline-secondary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiskeyLovers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="footerFixed">
        <%= render 'layouts/header' %>
      <main>
        <%= yield %>
      </main>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>